# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandbar < Formula
  desc "Deploy static sites to Sandbar"
  homepage "https://sandbar.cloud"
  version "1.13.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandbar-cloud/sandbar-cli/releases/download/v1.13.4/sandbar_1.13.4_darwin_amd64.tar.gz"
      sha256 "db37d0b9b4666ab807d54ae2c5581621c4fe706da768035d3e38e11091e2e7d5"

      define_method(:install) do
        bin.install "sandbar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandbar-cloud/sandbar-cli/releases/download/v1.13.4/sandbar_1.13.4_darwin_arm64.tar.gz"
      sha256 "a174a0733bad3a2768f425cf6a302fc130734c472fbfbdc16d8ce882980fa416"

      define_method(:install) do
        bin.install "sandbar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbar-cloud/sandbar-cli/releases/download/v1.13.4/sandbar_1.13.4_linux_amd64.tar.gz"
      sha256 "0aa06054fd852650c92adbd69edd920273e54aae134c7b3ce7c05a357b5ff54d"
      define_method(:install) do
        bin.install "sandbar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbar-cloud/sandbar-cli/releases/download/v1.13.4/sandbar_1.13.4_linux_arm64.tar.gz"
      sha256 "c7794e11a9709435edf8a2be31db5948df5949b72c435ba96b169a6d33326619"
      define_method(:install) do
        bin.install "sandbar"
      end
    end
  end
end
